[e1]This is a chatbot example

In [2]:
from transformers.utils import logging
logging.set_verbosity_error()
import torch
print(torch.__version__)

/Users/dogukanozkaya/anaconda3/envs/myenv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


2.2.1


In [3]:
from transformers import pipeline
chatbot=pipeline(task="conversational",model="facebook/blenderbot-400M-distill")


KeyboardInterrupt: 

In [ ]:
user_message="Hi, I love skiing and I am looking for a good ski resort in the Alps. Can you help me?"


In [ ]:
from transformers import Conversation
conversation = Conversation(user_message)
conversation = chatbot(conversation)

conversation.add_message({"role": "user", "content": "What else do you recommend?"})

print(chatbot(conversation))

Conversation id: 47c19826-cb07-4d0a-a7ea-dd94c58996d3
user: Hi, I love skiing and I am looking for a good ski resort in the Alps. Can you help me?
assistant:  Sure, what kind of resort are you looking for? There are so many to choose from.
user: What else do you recommend?
assistant:  Well, there are a lot of resorts in the Rocky Mountains in Colorado.



This is a translator example

In [ ]:
from transformers import pipeline
import torch
translator=pipeline(task="translation",model="facebook/nllb-200-distilled-600M",torch_dtype=torch.bfloat16)


In [ ]:
text="I am Dogukan Ozkaya. Coming from Turkey. Pleasure to meet you all Love the people in here."
translator(text,src_lang="eng_Latn",tgt_lang="tur_Latn")
print(translator(text,src_lang="eng_Latn",tgt_lang="tur_Latn"))

[{'translation_text': "Ben Dogukan Ozkaya, Türkiye'den geldim."}]


https://github.com/facebookresearch/flores/blob/main/flores200/README.md#languages-in-flores-200
Language abbr

In [ ]:
import gc
del chatbot
del translator
gc.collect()


228

In [ ]:
summarizer= pipeline(task="summarization",model="facebook/bart-large-cnn",torch_dtype=torch.bfloat16)

In [ ]:
long_text="The tower is 324 metres (1,063 ft) tall, about the same height as an 81-storey building, and the tallest structure in Paris. Its base is square, measuring 125 metres (410 ft) on each side. During its construction, the Eiffel Tower surpassed the Washington Monument to become the tallest"
summarizer(long_text,max_length=35,min_length=20)


[{'summary_text': 'The tower is 324 metres (1,063 ft) tall, about the same height as an 81-storey building. Its base is square, measuring'}]

: 

: 

In [ ]:
del summarizer
gc.collect()

139

In [ ]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = ['The cat sits outside',
              'A man is playing guitar',
              'The movies are awesome']

embeddings = model.encode(sentences, convert_to_tensor=True)

print(embeddings)


tensor([[ 0.1392,  0.0030,  0.0470,  ...,  0.0641, -0.0163,  0.0636],
        [ 0.0227, -0.0014, -0.0056,  ..., -0.0225,  0.0846, -0.0283],
        [-0.1043, -0.0628,  0.0093,  ...,  0.0020,  0.0653, -0.0150]],
       device='mps:0')


In [ ]:
sentences2 = ['The dog plays in the garden',
              'A woman watches TV',
              'The new movie is so great']
embeddings2 = model.encode(sentences2, convert_to_tensor=True)
print(embeddings2)

tensor([[ 0.0163, -0.0700,  0.0384,  ...,  0.0447,  0.0254, -0.0023],
        [ 0.0054, -0.0920,  0.0140,  ...,  0.0167, -0.0086, -0.0424],
        [-0.0842, -0.0592, -0.0010,  ..., -0.0157,  0.0764,  0.0389]],
       device='mps:0')


In [ ]:
from sentence_transformers import util

cosine_scores = util.pytorch_cos_sim(embeddings, embeddings2)
print(cosine_scores)
for i in range(len(sentences)):
    print("{} \t\t {} \t\t Score: {:.4f}".format(sentences[i],
                                                 sentences2[i],
                                                 cosine_scores[i][i]))


tensor([[ 0.2838,  0.1310, -0.0029],
        [ 0.2277, -0.0327, -0.0136],
        [-0.0124, -0.0465,  0.6571]], device='mps:0')
The cat sits outside 		 The dog plays in the garden 		 Score: 0.2838
A man is playing guitar 		 A woman watches TV 		 Score: -0.0327
The movies are awesome 		 The new movie is so great 		 Score: 0.6571


In [ ]:
del model
gc.collect()

15

In [ ]:
from datasets import load_dataset



/Users/dogukanozkaya/anaconda3/envs/myenv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
# This dataset is a collection of different sounds of 5 seconds
dataset = load_dataset("ashraq/esc50",
                      split="train[0:10]")
# dataset = load_from_disk("./models/ashraq/esc50/train")

In [ ]:
audio_sample = dataset[2]
display(audio_sample)

{'filename': '1-100210-A-36.wav',
 'fold': 1,
 'target': 36,
 'category': 'vacuum_cleaner',
 'esc10': False,
 'src_file': 100210,
 'take': 'A',
 'audio': {'path': None,
  'array': array([-0.00695801, -0.01251221, -0.01126099, ...,  0.215271  ,
         -0.00875854, -0.28903198]),
  'sampling_rate': 44100}}

In [ ]:
from IPython.display import Audio as IPythonAudio
IPythonAudio(audio_sample["audio"]["array"],
             rate=audio_sample["audio"]["sampling_rate"])

In [ ]:
from transformers import pipeline
zero_shot_classifier = pipeline(
    task="zero-shot-audio-classification",
    model="laion/clap-htsat-unfused")

In [ ]:
print(zero_shot_classifier.feature_extractor.sampling_rate)
audio_sample['audio']['sampling_rate']

48000


NameError: name 'audio_sample' is not defined

In [ ]:
from datasets import Audio
dataset = dataset.cast_column("audio", Audio(sampling_rate=48000))

NameError: name 'dataset' is not defined

In [ ]:

candidate_labels = ["Sound of a dogukan", "Sound of a cat", "Sound of a bird", "Sound of a vehicle", "Sound of a human"]
zero_shot_classifier(audio_sample["audio"]['array'],
                     candidate_labels=candidate_labels)

[{'score': 0.6439141631126404, 'label': 'Sound of a vehicle'},
 {'score': 0.2847440540790558, 'label': 'Sound of a human'},
 {'score': 0.029086049646139145, 'label': 'Sound of a bird'},
 {'score': 0.029021352529525757, 'label': 'Sound of a dogukan'},
 {'score': 0.013234362937510014, 'label': 'Sound of a cat'}]

In [ ]:
del zero_shot_classifier
gc.collect()

NameError: name 'zero_shot_classifier' is not defined

This is auto speech recognition

In [ ]:
dataset=load_dataset("librispeech_asr",split="train.clean.100",streaming=True)

/Users/dogukanozkaya/anaconda3/envs/myenv/lib/python3.10/site-packages/datasets/load.py:1461: FutureWarning: The repository for librispeech_asr contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/librispeech_asr
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(


In [ ]:
example=next(iter(dataset))
dataset_head=dataset.take(5)

In [ ]:
display(example)
# list(dataset_head)
list(dataset_head)[2]

{'file': '374-180298-0000.flac',
 'audio': {'path': '374-180298-0000.flac',
  'array': array([ 7.01904297e-04,  7.32421875e-04,  7.32421875e-04, ...,
         -2.74658203e-04, -1.83105469e-04, -3.05175781e-05]),
  'sampling_rate': 16000},
 'text': 'CHAPTER SIXTEEN I MIGHT HAVE TOLD YOU OF THE BEGINNING OF THIS LIAISON IN A FEW LINES BUT I WANTED YOU TO SEE EVERY STEP BY WHICH WE CAME I TO AGREE TO WHATEVER MARGUERITE WISHED',
 'speaker_id': 374,
 'chapter_id': 180298,
 'id': '374-180298-0000'}

{'file': '374-180298-0002.flac',
 'audio': {'path': '374-180298-0002.flac',
  'array': array([-2.44140625e-04, -2.44140625e-04, -1.83105469e-04, ...,
          1.83105469e-04,  3.05175781e-05, -1.52587891e-04]),
  'sampling_rate': 16000},
 'text': 'I WISHED ABOVE ALL NOT TO LEAVE MYSELF TIME TO THINK OVER THE POSITION I HAD ACCEPTED FOR IN SPITE OF MYSELF IT WAS A GREAT DISTRESS TO ME THUS MY LIFE GENERALLY SO CALM',
 'speaker_id': 374,
 'chapter_id': 180298,
 'id': '374-180298-0002'}

In [ ]:
from IPython.display import Audio as IPythonAudio
IPythonAudio(example["audio"]["array"],
             rate=example["audio"]["sampling_rate"])

In [ ]:
from transformers import pipeline

asr = pipeline("automatic-speech-recognition", model="distil-whisper/distil-small.en")

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [ ]:
print(asr.feature_extractor.sampling_rate)
print(example["audio"]["sampling_rate"])

16000
16000


In [ ]:
print(asr(example["audio"]["array"]))
print(example["text"])


{'text': ' Chapter 16 I might have told you of the beginning of this liaison in a few lines, but I wanted you to see every step by which we came. I too agree to whatever Marguerite wished.'}
CHAPTER SIXTEEN I MIGHT HAVE TOLD YOU OF THE BEGINNING OF THIS LIAISON IN A FEW LINES BUT I WANTED YOU TO SEE EVERY STEP BY WHICH WE CAME I TO AGREE TO WHATEVER MARGUERITE WISHED


In [ ]:
import gradio as gr
demo=gr.Blocks()


In [ ]:
def transcribe_speech(filepath):
    if(filepath) is None:
        gr.Warning("Please upload an audio file")
        return
    output=asr(filepath)
    return output["text"]


In [ ]:
mic_transcribe=gr.Interface(fn=transcribe_speech,
                            inputs=gr.Audio(sources="microphone",type="filepath"),
                            outputs=gr.Textbox(label="Transcription",lines=5),
                            allow_flagging=False,
)

                            

/Users/dogukanozkaya/anaconda3/envs/myenv/lib/python3.10/site-packages/gradio/interface.py:374: UserWarning: The `allow_flagging` parameter in `Interface` nowtakes a string value ('auto', 'manual', or 'never'), not a boolean. Setting parameter to: 'never'.
  warnings.warn(


In [ ]:
file_transcribe=gr.Interface(fn=transcribe_speech,
                            inputs=gr.Audio(sources="upload",type="filepath",label="Audio file"),
                            outputs=gr.Textbox(label="Transcription",lines=5),
                            allow_flagging=False,
)

In [ ]:
with demo:
    gr.TabbedInterface([mic_transcribe,file_transcribe],["Transcribe from Microphone","Transcribe from File"])

demo.launch()


Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.


In [ ]:
demo.close()

Closing server running on port: 7860


In [ ]:
import soundfile as sf
import io 

audio, sampling_rate=sf.read('example.wav')

LibsndfileError: Error opening 'quahwa.m4a': System error.

In [ ]:
audio.shape

* Convert the audio from stereo to mono (Using librosa)

In [ ]:
import numpy as np

audio_transposed = np.transpose(audio)
audio_transposed.shape

In [ ]:
import librosa

In [ ]:
audio_mono = librosa.to_mono(audio_transposed)

In [ ]:
IPythonAudio(audio_mono,
             rate=sampling_rate)

In [ ]:
asr(audio_mono)


In [ ]:
audio_16KHz = librosa.resample(audio_mono,
                               orig_sr=sampling_rate,
                               target_sr=16000)

In [ ]:
asr(
    audio_16KHz,
    chunk_length_s=30, # 30 seconds
    batch_size=4,
    return_timestamps=True,
)["chunks"]

In [ ]:
import gradio as gr
demo = gr.Blocks()

In [ ]:
def transcribe_long_form(filepath):
    if filepath is None:
        gr.Warning("No audio found, please retry.")
        return ""
    output = asr(
      filepath,
      max_new_tokens=256,
      chunk_length_s=30,
      batch_size=8,
    )
    return output["text"]

In [ ]:
mic_transcribe_long = gr.Interface(
    fn=transcribe_long_form,
    inputs=gr.Audio(sources="microphone",
                    type="filepath"),
    outputs=gr.Textbox(label="Transcription",
                       lines=3),
    allow_flagging="never")

file_transcribe_long = gr.Interface(
    fn=transcribe_long_form,
    inputs=gr.Audio(sources="upload",
                    type="filepath"),
    outputs=gr.Textbox(label="Transcription",
                       lines=3),
    allow_flagging="never",
)

In [ ]:

with demo:
    gr.TabbedInterface(
        [mic_transcribe_long,
         file_transcribe_long],
        ["Transcribe Microphone",
         "Transcribe Audio File"],
    )
demo.launch()

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.


In [ ]:
demo.close()

Closing server running on port: 7860


In [ ]:
import gc
del asr
gc.collect()

NameError: name 'asr' is not defined

In [1]:
from transformers import pipeline
text2speech = pipeline("text-to-speech", model="kakao-enterprise/vits-ljs")

/Users/dogukanozkaya/anaconda3/envs/myenv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Some weights of the model checkpoint at kakao-enterprise/vits-ljs were not used when initializing VitsModel: ['flow.flows.0.wavenet.in_layers.0.weight_g', 'flow.flows.0.wavenet.in_layers.0.weight_v', 'flow.flows.0.wavenet.in_layers.1.weight_g', 'flow.flows.0.wavenet.in_layers.1.weight_v', 'flow.flows.0.wavenet.in_layers.2.weight_g', 'flow.flows.0.wavenet.in_layers.2.weight_v', 'flow.flows.0.wavenet.in_layers.3.weight_g', 'flow.flows.0.wavenet.in_layers.3.weight_v', 'flow.flows.0.wavenet.res_skip_layers.0.weight_g', 'flow.flows.0.wavenet.res_skip_layers.0.weight_v', 'flow.flows.0.wavenet.res_skip_layers.1.weight_g', 'flow.flows.0.wavenet.res_skip_layers.1.weight_v', 'flow.flows.0.wavenet.res_skip_layers.2.weight_g',

In [7]:
text = """
Researchers at the Allen Institute for AI, \
HuggingFace, Microsoft, the University of Washington, \
Carnegie Mellon University, and the Hebrew University of \
Jerusalem developed a tool that measures atmospheric \
carbon emitted by cloud servers while training machine \
learning models. After a model’s size, the biggest variables \
were the server’s location and time of day it was active.
"""



In [10]:
output=text2speech(text)
from IPython.display import Audio as IPythonAudio

IPythonAudio(output["audio"][0],
             rate=output["sampling_rate"])

RuntimeError: espeak not installed on your system